<div class="adminleft">
	<ul id="menu_left">
			<li class="big_link"><a href="">Khác </a></li>
			<li class="sub_link"><a href="<?=$this->moduleUrl?>/slide">Banner Ảnh</a></li>
			<li class="sub_link"><a href="<?=$this->moduleUrl?>/gallery">Thư Viện Ảnh</a></li>
			<li class="sub_link"><a href="<?=$this->moduleUrl?>/video">Video</a></li>
			<li class="sub_link"><a href="<?=$this->moduleUrl?>/caro">Đối Tác</a></li>
	</ul>
</div>