<?php
$customer = $_SESSION['cp__customer'];
$type = $this->type;
?>
<div class="social-top">
    <div class="social-top-comment">
        <?php if (!$customer['img']): ?>
            <img class="social-top-comment-avatar" src="<?= BASE_URL ?>/style/img/no-avatar.png" alt="">
        <?php else: ?>
            <img class="social-top-comment-avatar" src="<?= BASE_URL ?>/files/customer/<?= $customer['ID'] ?>/<?= $customer['img'] ?>" alt="">
        <?php endif; ?>

        <input data-toggle="modal" data-target="#popEdit<?= $post['ID'] ?>" class="social-top-comment-detail" name="content" type="text" placeholder="<?= $customer['name'] ?>, what’s on your mind?" autocomplete="off"/>

        <div class="social-form modal fade" id="popEdit<?= $post['ID'] ?>" tabindex="-1" role="dialog" aria-labelledby="popAvatarLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 class="modal-title" id="popAvatarLabel">New post</h3>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form class="form-comment" action="<?= BASE_URL ?>/vn/social/post/add" method="post" enctype="multipart/form-data">
                            <textarea  id ='editor-content' name="content" class="social-top-comment-detail">
                            </textarea>
                            <?= $this->Plugins->textEditorSocial('content') ?>
                            <br>


                            <label class="btn btn-primary">
                                <i class="fa fa-image"></i>  Images<input type="file" style="display: none;" name="files[]" multiple="multiple" />
                            </label>
                            <br><br>
                            <button class='btn btn-success' type="submit" value="Upload" >Submit</button>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="social-top-more">
        <div class="social-top-more-sub social-top-more-video">
            <img class="social-top-more-video-img" src="<?= BASE_URL ?>/style/img/social/icon9.png" alt="">Videos
        </div>
        <div class="social-top-more-sub social-top-more-photo">
            <img class="social-top-more-photo-img" src="<?= BASE_URL ?>/style/img/social/icon10.png" alt="">
            Photos
        </div>
        <div class="social-top-more-sub social-top-more-emo">
            <img class="social-top-more-emo-img" src="<?= BASE_URL ?>/style/img/social/icon11.png" alt="">Emotions
        </div>
    </div>
</div>