<div class="adminleft">
		<ul id="menu_left">
				<li class="big_link"><a href="">Đội TNTP </a></li>
				<li class="sub_link"><a href="<?=$this->moduleUrl?>/group/setting">Cài Đặt Phân Trang</a></li>
				<li class="sub_link"><a href="<?=$this->moduleUrl?>/group">Danh Sách Tin Tức</a></li>
			<?/*	<li class="sub_link"><a href="<?=$this->moduleUrl?>/union/cat">Danh Sách Thư Mục</a></li>
			*/?>
		</ul>
	</div>