<div class="footer">
    <div class="container">
        <div class="box-left">
            <a href="#" class="logo-ft"></a>
            <p class="des">
                Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics.
            </p>
            <div class="box-network">
                <h2 class="title">Social Media</h2>
                <div class="list">
                    <a href="#" class="icon wt">Twitter</a>
                    <a href="#" class="icon m">M</a>
                    <a href="#" class="icon youtobe">Youtube</a>
                    <a href="#" class="icon telegam">Telegam</a>
                    <a href="#" class="icon fb">Facebook</a>
                </div>
            </div>
        </div>
        <div class="box-right">
            <div class="item">
                <h2 class="title">About Us</h2>
                <a href="#" class="alink">Whitepaper</a>
                <a href="#" class="alink">Business Contact </a>
                <a href="#" class="alink">Careers</a>
            </div> 
            <div class="item">
                <h2 class="title">Products</h2>
                <a href="#" class="alink">Al-Trade</a>
                <a href="#" class="alink">Dashboard</a>
                <a href="#" class="alink">Social</a>
                <a href="#" class="alink">Marketplace<span class="item-comingson">Coming Soon</span></a>
                <a href="#" class="alink">Box<span class="item-comingson">Coming Soon</span></a>
                <a href="#" class="alink">Launchpad<span class="item-comingson">Coming Soon</span></a>
                <a href="#" class="alink">Trend Spotter<span class="item-comingson">Coming Soon</span> </a>
            </div> 
            <div class="item">
                <h2 class="title">Learn</h2>
                <a href="#" class="alink">Guide</a>
                <a href="#" class="alink">Academy</a>
                <a href="#" class="alink">News</a>
            </div> 
            <div class="item">
                <h2 class="title">Support </h2>
                <a href="#" class="alink">Feedback</a>
                <a href="#" class="alink">Support Center</a>
                <a href="#" class="alink">Request</a>
            </div> 
        </div>
        <div class="box-conpy-right">
            © 2023 The Alchemist - All Rights Reserved

        </div>
    </div>
</div> 