<head>
    <title>Al-Trade-Subsysterm</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--font-->
    <link rel="stylesheet" href="<?= BASE_URL ?>/style/css/new-css/font.css">
    <!--style--> 
    <link rel="stylesheet" href="<?= BASE_URL ?>/style/css/new-css/theme.css">
    <link rel="stylesheet" href="<?= BASE_URL ?>/style/css/new-css/style-home.css">  
    <link rel="stylesheet" href="<?= BASE_URL ?>/style/css/new-css/aos.css">
    <link rel="stylesheet" href="<?= BASE_URL ?>/style/css/new-css/swiper.min.css" >
   

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TheAlchemist</title>
    <link rel="shortcut icon" href="<?= BASE_URL ?>/favicon.ico" />

    <link rel="stylesheet" href="<?= BASE_URL ?>/style/new/css/style.css">



    <script src="<?= BASE_URL ?>/style/js/jquery-3.6.0.min.js"></script>
    <script src="<?= BASE_URL ?>/style/js/social.js"></script>

</head>