<div class="modal fade" id="connect-wallet" >
    <div class="modal-dialo box-connect-wallet">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">close</button>
            <h4 class="modal-title" id="myModalLabel">Import Your Wallet</h4>
            <div class="list">
                <div class="row">
                    <div class="col-6">
                        <div class="item">
                            <i class="icon MetaMask"></i>
                            <h3 class="title"><a href="#">MetaMask</a></h3>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="item">
                            <i class="icon WalletConnect"></i>
                            <h3 class="title"><a href="#">WalletConnect</a></h3>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="item">
                            <i class="icon BinanceChainWallet"></i>
                            <h3 class="title"><a href="#">Binance Chain Wallet</a></h3>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="item">
                            <i class="icon TrustWallet"></i>
                            <h3 class="title"><a href="#">TrustWallet</a></h3>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="item">
                            <i class="icon Coin98Wallet"></i>
                            <h3 class="title"><a href="#">Coin98 Wallet</a></h3>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="item">
                            <i class="icon HoubiWallet"></i>
                            <h3 class="title"><a href="#">Houbi Wallet</a></h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>