<a href="#" class="icon-back-top"><i class="icon-up-open-1"></i></a>
<script src="<?= BASE_URL ?>/style/css/js/jquery-1.11.0.min.js" type="text/javascript"></script>
<script src="<?= BASE_URL ?>/style/css/js/bootstrap.min.js" type="text/javascript"></script>
<script src="<?= BASE_URL ?>/style/css/js/defaul.js" type="text/javascript"></script>
<script src="<?= BASE_URL ?>/style/css/js/aos.js" type="text/javascript"></script>
<script>
    AOS.init();
</script>