<ul class="menu">
	<li class="maintab">
		<a href="<?=$this->moduleUrl?>/" class="h" ><img src="<?=BASE_URL?>/admin/home.png" style="margin-left:12px;padding-right:10px;"/></a>
	</li>
    <li class="maintab">
		<a href="<?=$this->moduleUrl?>/about" class="h" >Giới Thiệu</a>
			<br/><ul class="childbtab" style="display:none">
                <li><a href="<?=$this->moduleUrl?>/about/setting">&#187; Cài Đặt Phân Trang</a></li>
				<li><a href="<?=$this->moduleUrl?>/about">&#187; Danh Sách Trang Giới Thiệu</a></li>
				<li><a href="<?=$this->moduleUrl?>/about/add">&#187; Thêm Trang Giới Thiệu</a></li>
			</ul>
	</li>

        <li class="maintab">
		<a href="<?=$this->moduleUrl?>/product"  class="h" >Công thức</a>
			<br/><ul class="childbtab"  style="display:none">
				<li><a href="<?=$this->moduleUrl?>/product/setting">&#187; Cài Đặt Phân Trang</a></li>
				<li><a href="<?=$this->moduleUrl?>/product/post">&#187; Danh Sách công thức</a></li>
				<li><a href="<?=$this->moduleUrl?>/product/cat">&#187; Danh Sách Thư Mục</a></li>
			</ul>
	</li>
        <li class="maintab">
		<a href="<?=$this->moduleUrl?>/news"  class="h" >Tin tức</a>
			<br/><ul class="childbtab"  style="display:none">
				<li><a href="<?=$this->moduleUrl?>/news/setting">&#187; Cài Đặt Phân Trang</a></li>
				<li><a href="<?=$this->moduleUrl?>/news/post">&#187; Danh Sách tin tức</a></li>
				<li><a href="<?=$this->moduleUrl?>/news/cat">&#187; Danh Sách Thư Mục</a></li>
			</ul>
	</li>
        <li class="maintab">
		<a href="<?=$this->moduleUrl?>/knowledge"  class="h" >Kiến thức</a>
			<br/><ul class="childbtab"  style="display:none">
				<li><a href="<?=$this->moduleUrl?>/knowledge/setting">&#187; Cài Đặt Phân Trang</a></li>
				<li><a href="<?=$this->moduleUrl?>/knowledge/post">&#187; Danh Sách kiến thức</a></li>
				<li><a href="<?=$this->moduleUrl?>/knowledge/cat">&#187; Danh Sách Thư Mục</a></li>
			</ul>
	</li>
	<li class="maintab">
		<a href="<?=$this->moduleUrl?>/contact"  class="h" style="padding-left:30px;">Liên Hệ</a>
	</li>
    <li class="maintab">
		<a href="<?=$this->moduleUrl?>/customer" class="h" >Khách hàng</a>
			<br/><ul class="childbtab"  style="display:none">
				<li><a href="<?=$this->moduleUrl?>/customer/setting">&#187; Cài Đặt Phân Trang</a></li>
				<li><a href="<?=$this->moduleUrl?>/customer/post">&#187; Danh Sách khách hàng</a></li>
			</ul>
	</li>
	<li class="maintab">
		<a href="<?=$this->moduleUrl?>/slide"  class="h" style="padding-left:30px;">Khác</a>
			<br/><ul class="childbtab" style="display:none">
				<li><a href="<?=$this->moduleUrl?>/slide/">&#187; Banner ảnh</a></li>
				<li><a href="<?=$this->moduleUrl?>/link/">&#187; Link liên kết</a></li>
				<li><a href="<?=$this->moduleUrl?>/video">&#187; Video</a></li>
<!--				<li><a href="<?=$this->moduleUrl?>/gallery/">&#187; Gallery</a></li>
				<li><a href="<?=$this->moduleUrl?>/caro">&#187; Đối Tác</a></li>-->

			</ul>
	</li>
</ul>
