<div class="border_link_web">LIÊN KẾT</div><!--end border link web-->
<div class="clear"></div>
<div class="content_link_web">
	<div class="partner_box">
		<?=$this->action("footer","index","Sub",array( 'language'=>$this->language ))?>
	</div>
</div>	
<div class="clear"></div>
<div id="main_footer">
		<?=$this->action("contfooter","index","Sub",array( 'language'=>$this->language ))?>
<?/*	
		<!-- Histats.com  START  (standard)-->
		<script type="text/javascript">document.write(unescape("%3Cscript src=%27http://s10.histats.com/js15.js%27 type=%27text/javascript%27%3E%3C/script%3E"));</script>
		<a href="http://www.histats.com" target="_blank" title="web hit counter" ><script  type="text/javascript" >
		try {Histats.start(1,1521300,4,242,241,20,"00011111");
		Histats.track_hits();} catch(err){};
		</script></a>
		<noscript><a href="http://www.histats.com" target="_blank"><img  src="http://sstatic1.histats.com/0.gif?1521300&101" alt="web hit counter" border="0"></a></noscript>
		<!-- Histats.com  END  -->
*/?>
</div>
