<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
	<title><?=$this->translate($this->module)?></title>
	<?php include("_script.phtml");?>
</head>
<body>
	<div id="page">
    	<div id="header">
			<?=$this->action("header","index","Sub",array('language'=>$this->language,'moduleTitle'=>$this->module))?>
        </div><!--end header-->
        <div id="main_index">
				<?php include("_page.phtml") ?>
				<div class="right_main_index">	
				<?=$this->action("right","index","Sub",array('language'=>$this->language,'moduleTitle'=>$this->module))?>
				</div>	
			<div id="footer">
			<?php include("_footer.phtml");?>
			</div><!--end footer-->
    </div><!--end page-->
</body>
</html>