<!DOCTYPE html>
<html lang="en">
    <head>
        <title><?= $this->translate($this->module) ?></title>
        <?php include '_script.phtml'; ?>
    </head>

    <body>
        <?=
        $this->action("header", "index", "Sub", array(
            'language' => $this->language,
            'moduleTitle' => $this->module))
        ?>
        <div id="myCarousel" class="carousel slide" data-interval="3000" data-ride="carousel">
            <div class="carousel-inner">
                <div class="active item" style="height: 125px">
                    <img src="<?= BASE_URL ?>/style/images/1.jpg" width="100%">
                </div>
            </div>
            <?=
            $this->action("banner", "index", "Sub", array(
                'language' => $this->language,
                'moduleTitle' => $this->module))
            ?>
        </div>
        <section class="container" style="padding-top:10px !important;">
            <div class="content-tile">
                <img src="<?= BASE_URL ?>/style/images/contact.png">
                <div class="title" style="background: none">
                    <h4 ><?= $this->translate('Contact') ?></h4>
                </div>
            </div>
            <div id="map">
                <?=$this->info['link']?>
            </div>
            <div class="clear_both"></div>
            <div class="row">
                <div class="col-md-6">
                    <?php if ($this->language == 'vn'): ?>
                        <?= $this->info['contact_vn'] ?>
                    <?php else: ?>
                        <?= $this->info['contact_en'] ?>
                    <?php endif; ?>
                </div>
                <div class="col-md-6">
                    <form role="form" style="margin-top: 10px;">
                        <div class="form-group">
                            <input type="text" class="form-control"  placeholder="<?= $this->translate('Name') ?>">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control"  placeholder="Email">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="<?= $this->translate('Phone') ?>">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="<?= $this->translate('Title') ?>">
                        </div>
                        <div class="form-group">
                            <textarea class="form-control" rows="3" placeholder="<?= $this->translate('Content') ?>"></textarea>
                        </div>
                        <button type="submit" class="btn btn-default submit-button"><?= $this->translate('Send') ?></button>
                        <button type="submit" class="btn btn-default cancel-button"><?= $this->translate('Cancel') ?></button>
                    </form>
                </div>
            </div>
        </section>
        <?=
        $this->action("footer", "index", "Sub", array(
            'language' => $this->language,
            'moduleTitle' => $this->module))
        ?>
    </body>
</html>
