<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>TheAlchemist</title>
        <link rel="shortcut icon" href="<?= BASE_URL ?>/favicon.ico" />
        <link rel="stylesheet" href="<?= BASE_URL ?>/style/new/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="<?= BASE_URL ?>/style/new/css/style.css">
        <link rel="stylesheet" href="<?= BASE_URL ?>/style/new/css/icons.css">
        <link rel="stylesheet" href="<?= BASE_URL ?>/style/new/css/ui.css">

    </head>

    <body>
        <div id ='container'>
            <?php include 'p_header.phtml'; ?>


            <div id ='container-top'>
                <div class="container-about">
                    <div class="container-img-over">
                        <img src="<?= BASE_URL ?>/style/img/bg2.svg">
                    </div>
                    <div class="container-about-more">
                        <h1>TheAlchemist</h12>
                            <h3>A data-driven platform</h3>
                            <h5>Providing cryptocurrency investors and traders with the most relevant insights and recommendations.</h5>
                            <div class="container-about-register">
                                <p><a class='container-about-register-a' href="">Register</a> </p>
                                <p><a class='container-about-register-a' href="">Video Training</a></p>
                            </div>
                            <div class="container-about-comming">
                                <p>Comming soon on</p>
                                <p><a href=""><img src="<?= BASE_URL ?>/style/img/apple.png" alt="" style="width:14px"></a> </p>
                                <p><a href=""><img src="<?= BASE_URL ?>/style/img/android.png" alt="" style="width:14px"></a></p>
                            </div>
                            <div class="container-about-binance">
                                <div class='container-about-binance-title'>
                                    <span>Our data is directly exported from two of the most popular crypto trading platforms</span>
                                    <br><br><span style='color:#F3BA2F'>Binance.com</span> &
                                    <span style='color:#2483FF'>Huobi.com</span></div>
                                <div style='display: flex;padding-top:40px;'>
                                    <p style='padding-right: 20px;'><a href=""><img src="<?= BASE_URL ?>/style/img/binance.png" alt=""></a> </p>
                                    <p><a href=""><img src="<?= BASE_URL ?>/style/img/global.png" alt=""></a></p>
                                </div>
                            </div>

                    </div>
                </div>

                <div class="container-about-right">
                    <div class="container-about-right-img"><img src="<?= BASE_URL ?>/style/img/img21.1.png" alt="" ></div>
                </div>
                <div  class="row container-fluid-other">
                    <h2> What does TheAlchemist do?</h2>
                    <div>We provide traders with trustworthy information based on:</div>
                </div>
                <div  class="row container-fluid-other2">
                    <div class="container-fluid-other2-sub">
                        <img src="<?= BASE_URL ?>/style/img/img1.jpg" alt="" width='80'>
                        <div class="container-fluid-other2-sub-title">Data Analysis</div>
                        <div class="container-fluid-other2-sub-quote" style="padding-bottom:40px;">Insights derived from big data and confluent technical indicators</div>
                        <div class="container-fluid-other2-sub-link"><a href='#'>Financial Analysis</a></div>
                        <div class="container-fluid-other2-sub-link"><a href='#'>Alchemist AI-Trade</a></div>
                    </div>
                    <div class="container-fluid-other2-sub">
                        <img src="<?= BASE_URL ?>/style/img/img2.jpg" alt="" width='80'>
                        <div class="container-fluid-other2-sub-title">Financial Consultants</div>
                        <div class="container-fluid-other2-sub-quote" style="padding-bottom:25px;">Investment experts will give analysis, assess your investment strategies, and provide you with project information</div>
                        <div class="container-fluid-other2-sub-link"><a href='#'>TheAlchemist Social</a></div>
                        <div class="container-fluid-other2-sub-link"><a href='#'>TheAlchemist News</a></div>
                    </div>
                    <div class="container-fluid-other2-sub">
                        <img src="<?= BASE_URL ?>/style/img/img3.jpg" alt="" width='80'>
                        <div class="container-fluid-other2-sub-title" style="padding-bottom:0px;">Sharing Your Knowledge & Experience</div>
                        <div class="container-fluid-other2-sub-quote">Enhancing your investment knowledge with TheAlchemist Knowledge and learning strategies from top traders with validated track records</div>
                        <div class="container-fluid-other2-sub-link"><a href='#'>TheAlchemist Knowledge</a></div>
                        <div class="container-fluid-other2-sub-link"><a href='#'>TheAlchemist Skill Trade Books</a></div>
                    </div>
                </div>
                <div  class="row container-fluid-other">
                    <h2>TheAlchemist AI Trade</h2>
                    <div>Using powerful confluent technical indicators</div>
                </div>
                <div  class="row container-fluid-other3">
                    <div class="container-fluid-other3-sub">
                        <img src="<?= BASE_URL ?>/style/img/img4.png" alt="" style='width:470px;'>
                    </div>
                    <div class="container-fluid-other3-sub container-fluid-other3-sub-end">
                        <ul>
                            <li><a>Using powerful confluent technical indicators.</a></li>
                            <li><a>Providing essential investment knowledge.</a></li>
                            <li><a>Managing and reporting on your investment portfolio.</a></li>
                            <li><a>Customizing your investment parameters.</a></li>
                            <li><a>Keeping track of market data in real time.</a></li>
                            <li><a>Interacting with fellow traders and investors via our social
                                    trading platform, ask, learn and share.</a></li>
                            <li><a>Providing an IDO/SHO platform that connects investors and startups.</a></li>
                        </ul>
                    </div>
                </div>
                <div  class="row container-fluid-other">
                    <h2>Alchemist's tokens are used for:</h2>
                </div>
                <div  class="row container-fluid-other2 container-fluid-other4">
                    <div class="container-fluid-other4-sub">
                        <img src="<?= BASE_URL ?>/style/img/img5.jpg" alt="" width='80'>
                        <div class="container-fluid-other2-sub-title">Paying your platform fee on</div>
                        <div class="container-fluid-other2-sub-link"><a href='#'>TheAlchemist</a></div>
                    </div>
                    <div class="container-fluid-other4-sub">
                        <img src="<?= BASE_URL ?>/style/img/img6.jpg" alt="" width='80'>
                        <div class="container-fluid-other2-sub-title">Purchasing skill books on</div>
                        <div class="container-fluid-other2-sub-link"><a href='#'>TheAlchemist maketplace</a></div>
                    </div>
                    <div class="container-fluid-other4-sub">
                        <img src="<?= BASE_URL ?>/style/img/img7.jpg" alt="" width='80'>
                        <div class="container-fluid-other2-sub-title">Participating in SHO on</div>
                        <div class="container-fluid-other2-sub-link"><a href='#'>TheAlchemist Launchpad</a></div>
                    </div>
                </div>
            </div>

        </div>

        <div  class="row container-fluid-other5">
            <div class='container-fluid-other5-content'>TheAlchemist's tokens are built on the Binance Smart Chain ecosystem.</div>
        </div>
        <div  class="row container-fluid-teams">
            <h2>FOUNDING TEAMS</h2>
            <div class="container-fluid-team">
                <div class="container-fluid-team-sub">
                    <img class ="container-fluid-team-sub-img" src="<?= BASE_URL ?>/style/img/img8.jpg" alt="" width='120'>
                    <div class="container-fluid-team-sub-title">Phùng Văn Thiện</div>
                    <div class="container-fluid-team-sub-link"><a href='#'>CEO</a></div>
                    <div class="container-fluid-team-sub-content">
                        <ul>
                            <li>CEO</li>
                            <li>CEO</li>
                        </ul>
                    </div>
                </div>
                <div class="container-fluid-team-sub">
                    <img class ="container-fluid-team-sub-img" src="<?= BASE_URL ?>/style/img/img8.jpg" alt="" width='120'>
                    <div class="container-fluid-team-sub-title">Phùng Văn Thiện</div>
                    <div class="container-fluid-team-sub-link"><a href='#'>CEO</a></div>
                    <div class="container-fluid-team-sub-content">
                        <ul>
                            <li>CEO</li>
                            <li>CEO</li>
                        </ul>
                    </div>
                </div>
                <div class="container-fluid-team-sub">
                    <img class ="container-fluid-team-sub-img" src="<?= BASE_URL ?>/style/img/img8.jpg" alt="" width='120'>
                    <div class="container-fluid-team-sub-title">Phùng Văn Thiện</div>
                    <div class="container-fluid-team-sub-link"><a href='#'>CEO</a></div>
                    <div class="container-fluid-team-sub-content">
                        <ul>
                            <li>CEO</li>
                            <li>CEO</li>
                        </ul>
                    </div>
                </div>
                <div class="container-fluid-team-sub">
                    <img class ="container-fluid-team-sub-img" src="<?= BASE_URL ?>/style/img/img8.jpg" alt="" width='120'>
                    <div class="container-fluid-team-sub-title">Phùng Văn Thiện</div>
                    <div class="container-fluid-team-sub-link"><a href='#'>CEO</a></div>
                    <div class="container-fluid-team-sub-content">
                        <ul>
                            <li>CEO</li>
                            <li>CEO</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div> <!-- End team -->
        <div  class="row container-fluid-teams">
            <h2>advisor</h2>
            <div class="container-fluid-team">
                <div class="container-fluid-team-sub">
                    <img class ="container-fluid-team-sub-img" src="<?= BASE_URL ?>/style/img/advisor/img1.png" alt="" width='120'>
                    <div class="container-fluid-team-sub-title">Alex Nguyen</div>
                    <div class="container-fluid-team-sub-link"><a href='#'>CTO GoJapan</a></div>
                    <div class="container-fluid-team-sub-content">
                        <ul>
                            <li>CEO</li>
                        </ul>
                    </div>
                </div>
                <div class="container-fluid-team-sub">
                    <img class ="container-fluid-team-sub-img" src="<?= BASE_URL ?>/style/img/advisor/img2.png" alt="" width='120'>
                    <div class="container-fluid-team-sub-title">Christian Ho</div>
                    <div class="container-fluid-team-sub-link"><a href='#'>Co-Founder
                            Unicorn Game Studios</a></div>
                    <div class="container-fluid-team-sub-content">
                        <ul>
                            <li>CEO</li>
                        </ul>
                    </div>
                </div>
                <div class="container-fluid-team-sub">
                    <img class ="container-fluid-team-sub-img" src="<?= BASE_URL ?>/style/img/advisor/img3.png" alt="" width='120'>
                    <div class="container-fluid-team-sub-title">Gadget Vu</div>
                    <div class="container-fluid-team-sub-link"><a href='#'>CEO</a></div>
                    <div class="container-fluid-team-sub-content">
                        <ul>
                            <li>CEO</li>
                        </ul>
                    </div>
                </div>
                <div class="container-fluid-team-sub">
                    <img class ="container-fluid-team-sub-img" src="<?= BASE_URL ?>/style/img/advisor/img4.png" alt="" width='120'>
                    <div class="container-fluid-team-sub-title">Hung Nguyen</div>
                    <div class="container-fluid-team-sub-link"><a href='#'>CEO & Founder
                            Gymstore</a></div>
                    <div class="container-fluid-team-sub-content">
                        <ul>
                            <li>CEO</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div> <!-- End advison -->
        <div  class="row container-fluid-other5" style="margin-top: 40px;">
            <div class='container-fluid-other5-content container-fluid-advison-content'>BACKEND BY</div>
            <div class='container-fluid-advison-items'>
                <div class='container-fluid-advison-item'>
                    <div class='container-fluid-advison-item-sub'>
                        <img src="<?= BASE_URL ?>/style/img/img22.png" alt="" height="62" width='100%'>
                    </div>
                </div>
                <div class='container-fluid-advison-item'>
                    <img src="<?= BASE_URL ?>/style/img/img23.png" alt="">
                </div>
                <div class='container-fluid-advison-item'></div>
                <div class='container-fluid-advison-item'></div>
                <div class='container-fluid-advison-item'></div>
                <div class='container-fluid-advison-item'></div>
            </div>
            <div class='container-fluid-advison-items'>
                <?php for ($i = 1; $i <= 6; $i++): ?>
                    <div class='container-fluid-advison-item'></div>
                <?php endfor; ?>
            </div>
        </div>
        <?php include 'p_footer.phtml'; ?>
    </div>



</body>

</html>
