<div class="adminleft">
		<ul id="menu_left">
				<li class="big_link"><a href="">Dự án </a></li>
				<li class="sub_link"><a href="<?=$this->moduleUrl?>/project/setting">Cấu hình trang</a></li>
				<li class="sub_link"><a href="<?=$this->moduleUrl?>/project/cat">Các dự án</a></li>
				<li class="sub_link"><a href="<?=$this->moduleUrl?>/project/post">Các bài viết</a></li>
				<!--<li class="sub_link"><a href="<?=$this->moduleUrl?>/project/files">Ảnh dự án</a></li>-->
		</ul>
	</div>