<div class="adminleft">
		<ul id="menu_left">
				<li class="big_link"><a href="">Cổ đông </a></li>
				<li class="sub_link"><a href="<?=$this->moduleUrl?>/shareholder/setting">Cài Đặt Phân Trang</a></li>
				<li class="sub_link"><a href="<?=$this->moduleUrl?>/shareholder">Danh Sách Bài Viết</a></li>
				<li class="sub_link"><a href="<?=$this->moduleUrl?>/shareholder/cat">Danh Sách Thư Mục</a></li>
		</ul>
	</div>