<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="one"><h5><b>Thông tin liên hệ</b></h5></div>
                <div class="one">Email: contact@pvpe.vn | Website: pvpe.vn</div>
                <div class="one">Trụ sở: S3 tầng 17 tòa nhà 319 số 63 Lê Văn Lương, phường Trung Hòa, quận Cầu Giấy, Hà Nội </div>
                <div class="one">Điện thoại: 04.35772222 </div>
                <div class="one">Fax: 04.35572222 </div>
            </div>
            <div class="col-lg-3">
                <div class="one"><h5><b>Liên kết</b></h5></div>
                <div class="one"><a style='color:rgba(255,255,255,.7)' href="<?=$this->info['yh01']?>">Facebook</a></div>
                <div class="one">Hòm thư</div>
                <div class="one"><a style='color:rgba(255,255,255,.7)' href="http://pvpe.1office.vn">Văn phòng điện tử OneOffice</a></div>
            </div>
            <div class="col-lg-3">
                <div class="one"><h5><b><?= $this->translate('Visitor Statistics') ?></b></h5></div>
                <div class="one"><?= $this->translate('Total visitor') ?>: <?=$this->total ?></div>
                <!--<div class="one"><?= $this->translate('Online') ?>: <?=$this->totalc ?></div>-->
            </div>
        </div>
		<div class="copyright" style="padding-top:5px;">© Copyright 1997 Pvpe.vn, All rights reserved <br>
		® Pvpe giữ bản quyền nội dung trên website này
	</div>
    </div>
	
</footer>
<script type='text/javascript' src="http://maps.google.com/maps/api/js?sensor=false&#038;ver=1.8.3"></script>
<script type='text/javascript' src="<?=BASE_URL?>/style/js/map.js"></script>
</body>
</html>
