<!-- CAT MENU-->
<div class="clear-fix">
    <div class="row">
        <div class="col-lg-6 col-xs-6 col-sm-6 col-md-6">
            <a href="<?= BASE_URL ?>/<?= $this->language ?>/<?php echo ($this->language == "vn" ? 'gioi-thieu' : 'About'); ?>" class="box titles color-palegreen test" data-size="1">
                <h3 class="fa fa-briefcase fa-4x"></h3>
                <div class="tt"><?= $this->translate('About Us') ?></div>
            </a>
        </div>
        <div class="col-lg-6 col-xs-6 col-sm-6 col-md-6">
            <a href="<?= BASE_URL ?>/<?= $this->language ?>/<?php echo ($this->language == "vn" ? 'linh-vuc-kinh-doanh' : 'Services'); ?>" class="box titles color-aqua" data-size="1">
                <h3 class="fa fa-globe fa-4x"></h3>
                <div class="tt"><?= $this->translate('Services') ?></div>
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6 col-xs-6 col-sm-6 col-md-6">
            <a href="<?= BASE_URL ?>/<?= $this->language ?>/<?php echo ($this->language == "vn" ? 'co-dong' : 'Shareholder'); ?>" class="box titles color-conflowerblue" data-size="1">
                <h3 class="fa fa-puzzle-piece fa-4x"></h3>
                <div class="tt"><?= $this->translate('Shareholder') ?></div>
            </a>
        </div>
        <div class="col-lg-6 col-xs-6 col-sm-6 col-md-6">
            <a href="<?= BASE_URL ?>/<?= $this->language ?>/<?php echo ($this->language == "vn" ? 'du-an' : 'Project'); ?>" class="box titles color-red" data-size="1">
                <h3 class="fa fa-building fa-4x"></h3>
                <div class="tt"><?= $this->translate('Project') ?></div>
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6 col-xs-6 col-sm-6 col-md-6">
            <a href="<?= BASE_URL ?>/<?= $this->language ?>/<?php echo ($this->language == "vn" ? 'hoat-dong' : 'News'); ?>" class="box titles color-orange" data-size="1">
                <h3 class="fa fa-bullhorn fa-4x"></h3>
                <div class="tt"><?= $this->translate('Activities') ?></div>
            </a>
        </div>
        <div class="col-lg-6 col-xs-6 col-sm-6 col-md-6">
            <a href="<?= BASE_URL ?>/<?= $this->language ?>/<?php echo ($this->language == "vn" ? 'nhan-su' : 'Career'); ?>" class="box titles color-plum" data-size="1">
                <h3 class="fa fa-users fa-4x"></h3>
                <div class="tt"><?= $this->translate('Career') ?></div>
            </a>
        </div>
    </div>

</div>