<div class="adminleft">
		<ul id="menu_left">
				<li class="big_link"><a href="">Download Tài Liệu </a></li>
				<li class="sub_link"><a href="<?=$this->moduleUrl?>/download/setting">Cài Đặt Phân Trang</a></li>
				<li class="sub_link"><a href="<?=$this->moduleUrl?>/download">Danh Sách Bài Viết</a></li>
				<li class="sub_link"><a href="<?=$this->moduleUrl?>/download/cat">Danh Sách Thư Mục</a></li>
		</ul>
	</div>