<?php if( isset($this->message ) ):?>
<div class="error">	<?=$this->translate($this->message);?></div>
<?php endif;?>
<?php if( $this->message != "ERROR_MSQL" AND $this->message != "ERROR_NOT_EXISTS" ):?>
<div class="wrap_admintab">
	<?php include "_menu.phtml"?>	
		<div class="adminright">
		
			<div class="admintab" style="min-height:376px;padding:0px;">
					<form action="<?=$this->actionUrl?>" method="post" enctype="multipart/form-data">
					<input type="hidden" name="ID" value="<?=$this->ID?>"/>
					<table cellpadding="8" border="1" bordercolor="#d9d9d9" width="100%">
						<tr>
							<td><label><?=$this->translate("Title")?></label></td>
							<td><input type="text" name="title" size="60" class="itext" value="<?=$this->title?>" /></td>
						</tr>
						
						<tr>
							<td><label><?=$this->translate("Parent")?></label></td>
							<td><?=$this->catOptions?></td>
						</tr>
						<tr>
							<td><label><?=$this->translate("Lang")?></label></td>
							<td><?=$this->translate("Language.{$_SESSION['cp_lang']}")?></td>
						</tr>
						<tr>
							<td><label><?=$this->translate("Date")?></label></td>
							<td><input type="text" class="itext date_picker" value="<?=$this->date?>" name="date" size="20"/>
							</td>
						</tr>
						<tr>
							<td><label><?=$this->translate("Sticky")?></label></td>
							<td><input type="type" name="sticky" class="itext" value="<?=$this->sticky?>" size="1"/></td>
						</tr>
						<tr>
							<td><label><?=$this->translate("Status")?></label></td>
							<td>
								<select name="status">
									<option value="1"<?=$this->status == 1 ?" selected":""?>><?=$this->translate("Noo")?></option>	
									<option value="0"<?=$this->status == 0 ?" selected":""?>><?=$this->translate("Yess")?></option>
								</select>
							</td>
						</tr>
						
						<tr>
							<td><label><?=$this->translate("File")?></label></td>
							<td>
								<input type="file" name="file"/>
								<br/> <a href="/download.php?f=<?=$this->file?>"><?=$this->file?></a>
							</td>
						</tr>
						
						<tr>
							<td colspan="2" align="center">
								<input type="submit" value="" class="capnhat"/>
							</td>
						</tr>	
					</table>	
					</form>
			</div>
		</div>	
</div>				


<?php endif;?>