<div class="wrap_admintab">
    <?php include "_menu.phtml" ?>	
    <div class="adminright">

        <div class="admintab" style="min-height:376px;padding:0px;">	
            <div id="tkiem">
                <h3 class="add_link"><a href="<?= $this->controllerUrl ?>/add" class="add"></a></h3>
            </div>
            <table cellpadding="8" border="1" bordercolor="#d9d9d9" width="100%">
                <tr>
                    <th><?= $this->translate("#") ?></th>
                    <th><?= $this->translate("Title") ?></th>
                    <th><?= $this->translate("Up") ?></th>
                    <th><?= $this->translate("Down") ?></th>		
                    <th><?= $this->translate("Edit") ?></th>
                    <th><?= $this->translate("Delete") ?></th>
                </tr>
                <?php foreach ($this->posts as $post): ?>
                    <tr>
                        <td valign="top" align="center">
                            <a class="quick_ord" u="<?= $this->controllerUrl ?>/edit/?ID=<?= $post['info']['ID'] ?>"><?= $post['info']['ord'] ?></a>
                        </td>
                        <td valign="top">
                            <?= str_repeat("+", $post['ord']) ?>&nbsp;
                            <a class="quick_edit_title" u="<?= $this->controllerUrl ?>/edit/?ID=<?= $post['info']['ID'] ?>" <?= $post['info']['sticky'] == 1 ? " style='color:red'" : "" ?>>
                                <?= $post['info']['title'] ?>
                            </a>
                        </td>
                        <td align="center"><a href="<?= $this->controllerUrl ?>/up/?ID=<?= $post['info']['ID'] ?>" class="up"></a></td>
                        <td align="center"><a href="<?= $this->controllerUrl ?>/down/?ID=<?= $post['info']['ID'] ?>" class="down"></a></td>
                        <td align="center"><a href="<?= $this->controllerUrl ?>/edit/?ID=<?= $post['info']['ID'] ?>" class="edit"></a></td>
                        <td align="center"><a href="<?= $this->controllerUrl ?>/delete/?ID=<?= $post['info']['ID'] ?>" class="delete"></a></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>	
</div>	
