<div class="adminleft">
		<ul id="menu_left">
				<li class="big_link"><a href="">Album ảnh </a></li>
				<li class="sub_link"><a href="<?=$this->moduleUrl?>/gallery/cat">Thư mục</a></li>
				<li class="sub_link"><a href="<?=$this->moduleUrl?>/gallery/post">Các Album</a></li>
				<li class="sub_link"><a href="<?=$this->moduleUrl?>/gallery/files">Ảnh album</a></li>
				<li class="sub_link"><a href="<?=$this->moduleUrl?>/gallery/setting">Cấu hình trang</a></li>
		</ul>
	</div>