<?php if ( isset($this->message) ): ?>
    <div class="error">	<?= $this->translate($this->message); ?> </div>
<?php endif; ?>
<?php if ( ($this->message != "ERROR_MSQL") && ($this->message != "ERROR_NOT_EXISTS") ): ?>
    <div class="wrap_admintab">
        <?php include "_menu.phtml" ?>
        <div class="adminright">

            <div class="admintab" style="min-height:376px;padding:0px;">

                <form action="<?= $this->actionUrl ?>" method="post" enctype="multipart/form-data">
                    <input type="hidden" name="ID" value="<?= $this->ID ?>"/>
                    <table cellpadding="8" border="1" bordercolor="#d9d9d9" width="100%">
                        <tr>
                            <td width="100"><label>Tiêu đề</label></td>
                            <td>Tiếng việt <input type="text" name="title_vn" class="itext" size="40" value="<?= $this->title_vn ?>" />
                                <br/>Tiếng anh <input type="text" name="title_en" class="itext" size="40" value="<?= $this->title_en ?>" /></td>
                        </tr>

                        <tr>
                            <td><label><?= $this->translate("Post Number") ?></label></td>
                            <td><input type="text" value="<?= $this->post_number ?>" name="post_number" class="itext" size="5"/></td>
                        </tr>
                        <tr>
                            <td><label><?= $this->translate("Next Number") ?></label></td>
                            <td><input type="text" value="<?= $this->next_number ?>" name="next_number" class="itext" size="5"/></td>
                        </tr>
                        <tr>
                            <td><label><?= $this->translate("Order") ?></label></td>
                            <td><input type="text" value="<?= $this->ord ?>" name="ord" class="itext" size="5"/></td>
                        </tr>
                        <?php /*
                          <tr>
                          <td><label><?=$this->translate("Status")?></label></td>
                          <td>
                          <select name="status">
                          <option value="0"<?=$this->status == 0 ?" selected":""?>><?=$this->translate("Yess")?></option>
                          <option value="1"<?=$this->status == 1 ?" selected":""?>><?=$this->translate("Noo")?></option>
                          </select>
                          </td>
                          </tr>
                          <tr>
                          <td><label><?=$this->translate("Header")?></label></td>
                          <td>
                          <textarea name="header"></textarea>
                          <?=$this->Plugins->textEditor("header")?>
                          </td>
                          </tr>
                          <tr>
                          <td><label><?=$this->translate("Footer")?></label></td>
                          <td>
                          <textarea name="footer"></textarea>
                          <?=$this->Plugins->textEditor("footer")?>
                          </td>
                          </tr>
                         */ ?>
                        <tr>
                            <td colspan="2" align="center"><input type="submit" value="<?= $this->translate("Submit_Create") ?>"/></td>
                        </tr>

                    </table>
                </form>
            </div>
        </div>
    </div>
<?php endif; ?>