<div class="wrap_admintab">
	<?php include "_menu.phtml"?>
		<div class="adminright">

			<div class="admintab" style="min-height:376px;padding:0px;">
				<div id="tkiem">
					<ul >
						<form action="<?=$this->actionUrl?>" class="formajax">

						<li class="form_h">
							 <input type="text" name="s" class="itext hh_s" size="25" style="color:#8e8e8e; font-style:italic;padding:3px;" onfocus="if(this.value == ' Nhập từ khóa vào đây') this.value=''; this.select();" onBlur="if(this.value=='') this.value=' Nhập từ khóa vào đây';" value=" Nhập từ khóa vào đây" />&nbsp;<input type="submit" class="search" title="<?=$this->translate('Find post')?>"/>

						</li>
						</form>
					</ul>

						<h3 class="add_link"><a href="<?=$this->controllerUrl?>/add<?=$this->action?>" class="add"></a></h3>

				</div>
				<div style="clear:both"></div>
				<form action="<?=$this->controllerUrl?>/delete<?=$this->action?>" method="post" class="formajax">
				<?=$this->pageBar?>
<table cellpadding="8" border="1" bordercolor="#d9d9d9" style="border-collapse:collapse" width="100%" align="center">
<tr>
	<th><?=$this->translate("ID")?></th>
	<th><?=$this->translate("Title")?></th>
	<th>Quản lý ảnh</th>
	<th><?=$this->translate("Date")?></th>
	<th><?=$this->translate("Poster")?></th>
	<th><?=$this->translate("Editer")?></th>
	<th><?=$this->translate("Edit")?></th>
	<th><?=$this->translate("Delete")?></th>
	<th><input type="checkbox" onclick="checkAll(this)"/></th>
</tr>
<?php foreach( $this->posts as $key => $post ): ?>
	<tr>
		<td align="center"><?=$key+1?></td>
		<td>
			<a  u="<?=$this->controllerUrl?>/edit<?=$this->action?>/?ID=<?=$post['ID']?>">
				<?=$post['sticky'] !='0' ? '<b style="color:red">'.$post['sticky'].'. </b>' :'' ?><?=$post['title']?><?=$post['has_video']=='1' ?"<sup><i class='has_video'></i></sup>":""?><?=$post['has_img']=='1' ?"<sub><i class='has_image'></i></sub>":""?></a>
		</td>
		<td align="center" nowrap="nowrap">
			<label class="ajax"><a href="<?=$this->controllerUrl?>/files/?parent_id=<?=$post['ID']?>"><img src="<?=BASE_URL?>/admin/attach.png" width="24"/></a></label>
		</td>
		<td align="center"><?=$post['date'] <= $this->Plugins->time() ? date("H:i:s d/m/Y",$post['date']) : ("<span class='nextdate'>".date("H:i:s d/m/Y",$post['date'])."</span>") ?></td>
		<td align="center"><span title="<?=@date("H:i:s d/m/Y",$post['date_post'])?>"><?=@$post['user_post']?></span></td>
		<td align="center"><?php if(isset($post['user_edit'])):?><span title="<?=date("H:i:s d/m/Y",$post['date_edit'])?>"><?=$post['user_edit']?></span><?php endif;?></td>
		<td align="center">
			<a href="<?=$this->controllerUrl?>/edit<?=$this->action?>/?ID=<?=$post['ID']?>" class="edit"></a>
		</td>
		<td align="center">
			<a href="<?=$this->controllerUrl?>/delete<?=$this->action?>/?ID=<?=$post['ID']?>" class="delete"></a>
		</td>
		<td align="center"><input type="checkbox" size="1" value="<?=$post['ID']?>" name="ID[]"/></td>
	</tr>
<?php endforeach; ?>
<?php if( isset($key) ): ?>
	<tr>
		<td colspan="7" align="right">
			<label class="ajax"><a href="<?=$this->controllerUrl?>/files/"><img src="<?=BASE_URL?>/admin/attach.png" width="24"/> Duyệt tất cả ảnh</a></label>
		</td>
		<td align="center">
			<input type="submit" class="deleteall" onclick="$('input.moveall').remove()" title="<?=$this->translate('Delete selected posts')?>"/>
		</td>
		<td align="center">
			<input type="submit" name="act_move" class="moveall" title="<?=$this->translate('Move selected posts')?>"/>
		</td>
	</tr>
<?php else:?>
	<tr>
		<td colspan="9" align="center">
			<?=$this->translate("Nothing found")?>
		</td>
	</tr>
<?php endif;?>
</table>
<?=$this->pageBar?>
</form>
	</div>
		</div>
</div>