<?php
$customer = $_SESSION['cp__customer'];
?>
<div class="social-content">
    <div class="row social-content-sub">
        <div class="col-xl-3 col-lg-3 col-md-3 social-content-left">
            <?=
            $this->action("left", "index", "Social", array(
                'language' => $this->language,
                'id_active' => $this->id_active,
                'moduleTitle' => $this->module))
            ?>
        </div>
        <div class="col-xl-6 col-lg-6 col-md-6 social-content-center">
            <?=
            $this->action("top", "index", "Social", array(
                'language' => $this->language,
                'id_active' => $this->id_active,
                'moduleTitle' => $this->module))
            ?>
            <?=
            $this->action("items", "index", "Social", array(
                'language' => $this->language,
                'id_active' => $this->id_active,
                'moduleTitle' => $this->module))
            ?>
        </div>
        <div class="col-xl-3 col-lg-3 col-md-3 social-content-right">
            <div class="social-content-sub-right">
                <div class="social-content-sub-right-info">
                    <img src="<?= BASE_URL ?>/style/img/social/week.jpg" alt="">
                    <img src="<?= BASE_URL ?>/style/img/social/month.jpg" alt="">
                </div>
                <div class="social-content-sub-right-notice">
                    <div class="social-content-sub-right-notice-title">
                        Notifications
                    </div>
                    <div class="social-content-sub-right-notice-detail">
                        <div class="social-content-sub-right-notice-detail-item">
                            <img src="<?= BASE_URL ?>/style/img/img8.jpg" alt="">
                            <div class="social-content-sub-right-notice-detail-item-title">
                                <p class="title"><a href="">Sold 300  AAI Coins</a></p>
                                <p class="time">1 minutes ago</p>
                            </div>
                        </div>
                        <div class="social-content-sub-right-notice-detail-item">
                            <img src="<?= BASE_URL ?>/style/img/img8.jpg" alt="">
                            <div class="social-content-sub-right-notice-detail-item-title">
                                <p class="title"><a href="">Sold 300  AAI Coins</a></p>
                                <p class="time">1 minutes ago</p>
                            </div>
                        </div>
                        <div class="social-content-sub-right-notice-detail-item">
                            <img src="<?= BASE_URL ?>/style/img/img8.jpg" alt="">
                            <div class="social-content-sub-right-notice-detail-item-title">
                                <p class="title"><a href="">Post 05 Image</a></p>
                                <p class="time">5 minutes ago</p>
                            </div>
                        </div>
                        <div class="social-content-sub-right-notice-detail-item">
                            <img src="<?= BASE_URL ?>/style/img/img8.jpg" alt="">
                            <div class="social-content-sub-right-notice-detail-item-title">
                                <p class="title"><a href="">Sold 02 Skill Trade Books</a></p>
                                <p class="time">2 hours ago</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>