<div class="adminleft">
		<ul id="menu_left">
				<li class="big_link"><a href="">Nhân sự </a></li>
				<li class="sub_link"><a href="<?=$this->moduleUrl?>/personnel/setting">Cài Đặt Phân Trang</a></li>
				<li class="sub_link"><a href="<?=$this->moduleUrl?>/personnel">Danh Sách Bài Viết</a></li>
				<li class="sub_link"><a href="<?=$this->moduleUrl?>/personnel/cat">Danh Sách Thư Mục</a></li>
		</ul>
	</div>