<?php if ( isset($this->message) ): ?>
    <div class="error">	<?= $this->translate($this->message); ?> </div>
<?php endif; ?>
<?php if ( $this->message != "MYSQL_ERROR" ): ?>
    <div class="wrap_admintab">

        <div class="adminleft">
            <ul id="menu_left">

                <li class="big_link"><a href="">Giới Thiệu</a></li>
                <li class="sub_link"><a href="<?= $this->moduleUrl ?>/about">Danh Sách Trang Giới Thiệu</a></li>
                <li class="sub_link"><a href="<?= $this->moduleUrl ?>/about/add">Thêm Trang Giới Thiệu</a></li>
            </ul>
        </div>
        <div class="adminright">
            <div class="admintab" style="min-height:376px;padding:0px;">
                <form action="<?= $this->actionUrl ?>" method="post" enctype="multipart/form-data">
                    <input type="hidden" name="ID" value="<?= $this->ID ?>"/>
                    <table cellpadding="8" border="1" bordercolor="#d9d9d9" width="100%">
                        <tr>
                            <td width="100"><label><?= $this->translate("Title") ?></label></td>
                            <td>Tiếng việt <input type="text" name="title_vn" class="itext" size="40" value="<?= $this->title_vn ?>" />
                                <br/>Tiếng anh <input type="text" name="title_en" class="itext" size="40" value="<?= $this->title_en ?>" /></td>
                        </tr>
                        <tr>
                            <td><label>Meta Description(Mô tả)</label></td>
                            <td><input type="text" name="desc" class="itext" size="60" value="<?= $this->desc ?>" /></td>
                        </tr>
                        <tr>
                            <td><label>Meta Keyword(Từ khóa)</label></td>
                            <td><input type="text" name="desc" class="itext" size="60" value="<?= $this->keyword ?>" /></td>
                        </tr>
                        <?php /* <tr>
                          <td><label><?=$this->translate("Lang")?></label></td>
                          <td><?=$this->translate("Language.{$_SESSION['cp_lang']}")?></td>
                          </tr>
                         */ ?>
                        <tr>
                            <td><label><?= $this->translate("Parent") ?></label></td>
                            <td><?= $this->catOptions ?></td>
                        </tr>
                        <tr>
                            <td><label><?= $this->translate("Sticky") ?></label></td>
                            <td><input type="type" name="sticky" class="itext" value="<?= $this->sticky ?>" size="1"/></td>
                        </tr>
                        <?php /*
                          <tr>
                          <td><label><?=$this->translate("Quote")?></label></td>
                          <td>
                          <textarea name='quote'><?=$this->escape( $this->quote )?></textarea>
                          <?=$this->Plugins->textEditor("quote")?>
                          </td>
                          </tr>
                         */ ?>
                        <tr>
                            <td><label><?= $this->translate("Img") ?></label></td>
                            <td>
                                <input type="file" name="img"/><br/>
                                <img src="<?= BASE_URL ?>/<?= $this->dirImage ?>/<?= $this->img ?>"/>
                            </td>
                        </tr>
                        <tr>
                            <td><label>Nội dung (tiếng việt)</label></td>
                            <td>
                                <textarea name='content_vn'><?= $this->content_vn ?></textarea>
                                <?= $this->Plugins->textEditor("content_vn") ?>
                            </td>
                        </tr>
                        <tr>
                            <td><label>Nội dung (tiếng anh)</label></td>
                            <td>
                                <textarea name='content_en'><?= $this->content_en ?></textarea>
                                <?= $this->Plugins->textEditor("content_en") ?>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2" align="center"><input type="submit" value="" class="capnhat"/></td>
                        </tr>
                    </table>
                </form><?php endif; ?>
        </div>
    </div>
</div>