<div class="adminleft">
		<ul id="menu_left">
				<li class="big_link"><a href="">Kiến thức </a></li>
				<li class="sub_link"><a href="<?=$this->moduleUrl?>/knowledge/setting">Cài Đặt Phân Trang</a></li>
				<li class="sub_link"><a href="<?=$this->moduleUrl?>/knowledge">Danh Sách kiến thức</a></li>
				<li class="sub_link"><a href="<?=$this->moduleUrl?>/knowledge/cat">Danh Sách Thư Mục</a></li>
		</ul>
	</div>