<?php
$customer = $_SESSION['cp__customer'];
?>
<div class="social-content">
    <div class="row social-content-sub">

        <div class="social-content-center">
            <?=
            $this->action("top", "index", "Social", array(
                'language' => $this->language,
                'id_active' => $this->id_active,
                'moduleTitle' => $this->module))
            ?>
            <?=
            $this->action("items", "index", "Social", array(
                'language' => $this->language,
                'id_active' => $this->id_active,
                'moduleTitle' => $this->module))
            ?>
        </div>
    </div>
</div>