<?php
$prices = $this->prices;
$formulars = $this->formulars;
$posts = $this->posts;
$postBtcs = $this->postBtcs;
$postCurrent = $this->postCurrent;
$histories = $this->histories;
$symbol = $this->symbol;
$rsi7 = $this->rsi;
//$symbol = 'BTCUSDT';
$tab = $this->tab;
$type = $this->type;
$activeList = $this->aclist;
$postMyLists = $this->postMyLists;
$postMyProLists = $this->postMyProLists;
$patternQueryString = $this->patternQueryString;
$patternsPosts = $this->patternsPosts;
$patternCurrent = empty($this->patternCurrent) && !empty($patternsPosts) ? $patternsPosts[0] : $this->patternCurrent;

//xử lý referer
$referer = $_SERVER['SCRIPT_URI'];
//Xử lý request
$studies = $this->Plugins->get('study', "");

if (!$studies && $postCurrent) {
    if ($post['view_id']) {
         echo $post['view_id'];
        if ($post['view_id'] == 1) {
            $studies = 'RSI, PSAR';
        } elseif ($post['view_id'] == 2) {
             $studies = 'RSI, SPAR';
        } elseif ($post['view_id'] == 3) {
            $studies = 'RSI14';
        } elseif ($post['view_id'] == 4) {
            $studies = 'RSI14, SPAR';
        }
    }
}

$study = [];
if ($studies) {
    if ($studies == 'RSI') {
        $studies = 'RSI,PSAR';
    }
    foreach (explode(',', $studies) as $a) {
        if ($a == 'RSI') {
            $study[] = [
                'id' => $a . "@tv-basicstudies",
                'inputs' => ['length' => 7]
            ];
        } elseif ($a == 'RSI14') {
            $study[] = [
                'id' => "RSI@tv-basicstudies",
                'inputs' => ['length' => 14]
            ];
        } else {
            $study[] = [
                'id' => $a . "@tv-basicstudies",
            ];
        }
    }
} else {
    $studies = 'RSI,PSAR';
    $study[] = [
        [
            'id' => "RSI@tv-basicstudies",
            'inputs' => ['length' => 7]
        ],
        [
            'id' => "PSAR@tv-basicstudies",
        ]
    ];
}


$interval = "1D";
if ($type == "H4") {
    $interval = "4H";
} elseif ($type == "H1") {
    $interval = "1H";
} elseif ($type == "30m") {
    $interval = "30";
}

$rightPosts = [];
if ($activeList == 'pro') {
    $rightPosts = $postMyProLists;
} elseif ($activeList == 'my') {
    $rightPosts = $postMyLists;
} else {
    $rightPosts = $posts;
}
?>
<!DOCTYPE html>
<html>
    <?php include __DIR__ . '/layouts/head.phtml'; ?>
    <link rel="stylesheet" href="<?= BASE_URL ?>/style/css/new-css/patterns.css">
	

    <title>Chart-Patterns</title>
<body>

<!--header-->
<?php include __DIR__ . '/layouts/headerPatterns.phtml'; ?>
<!--end header-->

<!--Al-trade_body-->
<div class="wapper">
    <script>
        /**
         * console.log("$patternsPosts", `<?php var_dump($patternsPosts); ?>`)
         *
         */
    </script>
        <!--Notice Box--> 
        <div class="container"> 
            <div class="altrade-body">
                    <div class="notice-box">
                        <a> Alchemist primary alert!<span style="color: #1A64F0;" href="#"> SEE MORE</span></a>
                    </div>    
                    <div class="confluence-bar">
                        <div style="display: flex;">
						 	
						 	<div class="confluence-box-2 <?= $studies == 'RSI,PSAR' ? "confluence-box-2-active" : "" ?>" >
                                <a href="#">Harmonic Chart Patterns</a>
                            </div>
														
							<div class="confluence-box-2 <?= $studies == 'RSI14' ? "confluence-box-2-active" : "" ?>" >
                                <a href="#">Head & Shoulder Chart Patterns</a>
                            </div>
							
                            <div  class="confluence-box-2"><a>Double Top & Bottom </a></div>
                            
                            <div  class="confluence-box-2"><a>Continuation Chart Patterns</a></div>
                            <div  class="confluence-box-2"><a>Reversal Chart Patterns</a></div>
                            <!--<div  class="confluence-box-2-active"><a class="<?= $studies == 'BULL' ? "confluence-box-2-active" : "" ?>" href="?symbol=<?= $symbol ?>&study=BULL">Bull Trap & Bear Trap</a></div>-->
                            <div  class="confluence-box-2 "><a>Other</a></div>
                        </div>
                        <div class="stablecoin-frame">
                            
                            <a type="button" class="stablecoin-button-1 
                                    <?= $tab == 'USDT' ? "stablecoin-button-1-active" : "" ?>" href="?tab=USDT">
                                
                                    <span class="label-satblecoin">
                                        <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/icon-usdt.svg">
                                    </span>
                                        <span style="font-size: 16;">Tether </span>
                                        <span style="color: #1A64F0;">USDT</span>
                                
                            </a>
                            
                            <a href="?tab=BTC" class="stablecoin-button-1 
                                                    <?= $tab == 'BTC' ? "stablecoin-button-1-active" : "" ?>">
                                
                                    <span class="label-satblecoin">
                                            <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/icon-btc.svg"> 
                                    </span>  
                                        <span>Bitcoin</span>
                                        <span style="color: #1A64F0;">BTC</span>
                                
                            </a>
                            <a href="?tab=BUSD" type="button" class="stablecoin-button-1 
                                                <?= $tab == 'BUSD' ? "stablecoin-button-1-active" : "" ?>">
                                
                                    <span class="label-satblecoin">
                                        <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/icon-busd.svg" alt="icon-busd.svg">
                                    </span>
                                        <span>Binance</span>
                                        <span style="color: #1A64F0;">USD</span>
                             <!--time-frame -->    
                            </a>
                                <img src="<?= BASE_URL ?>/style/css/new-images/Vector 62 (Stroke).svg" alt="Vector 62 (Stroke).svg">
                            
                            <a class="timeframe-button <?= $type == 'D1' ? "timeframe-button-active" : "" ?>" href="?study=RSI&symbol=<?= $symbol ?>&tab=<?= $tab ?>&type=D1&aclist=<?= $activeList ?>"><span>1D</span></a>
                            <a class="timeframe-button <?= $type == 'H4' ? "timeframe-button-active" : "" ?>" href="?study=RSI&symbol=<?= $symbol ?>&tab=<?= $tab ?>&type=H4&aclist=<?= $activeList ?>"><span>4H</span></a>
                            <a class="timeframe-button <?= $type == 'H1' ? "timeframe-button-active" : "" ?>" href="?study=RSI&symbol=<?= $symbol ?>&tab=<?= $tab ?>&type=H1&aclist=<?= $activeList ?>"><span>1H</span></a>
                            <a class="timeframe-button <?= $type == '30m' ? "timeframe-button-active" : "" ?>" href="?study=RSI&symbol=<?= $symbol ?>&tab=<?= $tab ?>&type=30m&aclist=<?= $activeList ?>"><span>30m</span></a>
                           
                                                   
                        </div>
                     <!-- left box -->
                     <div class="history-box">
                                <a style="font-family: 'Poppins'; font-size: 18px; ">Backtest</a>
                                
                                <table class="history-table" <?= $activeUSD ?>" id="usd">
                                    <thead>
                                        <tr class="text_headerlist">
                                            <th scope="col" style="color:#1A64F0;">Time</th>
                                            <th scope="col" style="color:#1A64F0;">Date</th>
                                            <th scope="col" style="color:#1A64F0;">Status</th>
                                        </tr>
                                    </thead>
                                    <tbody class="tr-bottom text_onlist">
                                                <?php if ($histories): ?>
                                            <?php foreach ($histories as $k => $post): ?>
                                                <?php
                                                if ($type == 'H4') {
                                                    $d2 = strtotime($post['date_h4'], '+4 hours') + 4;
                                                } else {
                                                    $d2 = strtotime('+1 day' , $post['date'] ) + 1;
                                                }
                                                ?>
                                                <tr style="border-bottom: 1px solid #F6F6F6;" class="<?= $postCurrent['ID'] == $post['ID'] ? "trade-coin-tr-active" : "" ?>">
                                                    <td class="align-middle">
                                                        <a class='trade-coin-a' href="?ID=<?php echo($post['ID']) ?>&symbol=<?php echo($post['symbol']) ?>&type=<?php echo($type) ?>&study=<?= $studies ?>" data-toggle="tooltip" data-placement="right" title="<?= $post['symbol'] ?>"><?php echo(date("d/m",$post['close_time'] / 1000 + 1)) ?></a>
                                                    </td>
                                                    <td class="align-middle">
                                                        <?php echo(date("H:i", $d2)) ?>

                                                    </td>
                                                    <td class="align-middle">
                                                        <?php if ($k % 1 == 0) : ?> Done
                                                        <?php elseif ($k % 2 == 1) : ?> Waiting
                                                        <?php else : ?> Fail
                                                        <?php endif; ?>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                        <?php else: ?>
                                            <tr>
                                                <td class="align-middle" colspan="3">
                                                    Nothing
                                                </td>
                                            </tr>

                                        <?php endif; ?>
                                    </tbody>
                                </table>
                              <!--  
                              <table class="history-table" <?= $activeUSD ?>" id="usd">
                                    <tbody class="tr-bottom text_onlist">
                                        <?php if ($leftPostDown): ?>
                                            <?php foreach ($leftPostDown as $postDown): ?>
                                                <tr style="border-bottom: 1px solid #F6F6F6;">
                                                    <td class="align-left">
                                                        <a href="?ID=<?= $postDown['id'] ?>&list=<?= $list ?>&symbol=<?= $post['symbol'] ?>&tab=<?= $tab ?>&type=<?= $type ?>&study=<?= $studies ?>"
                                                           style="color:<?= $postDown['model_type'] == "UP" ? '#00BD46' : '#CC0001' ?>;" 
                                                           class="trade-coin-a" 
                                                           data-placement="right" 
                                                           title="<?= $postDown['symbol'] ?>">
                                                            <?= get_quote(strip_tags($postDown['symbol']), 6) ?>
                                                        </a>
                                                    </td>
                                                    <td class="align-middle" style="color:<?= $postDown['model_type'] == "UP" ? '#00BD46' : '#CC0001' ?>;">
                                                        <span class="pr-2" data-placement="right">
                                                            <span class='desc'><?= date('H:i - d/m' , strtotime($postDown['date_find'])) ?></span>
                                                        </span>
                                                    </td>
                                                </tr>


                                            <?php endforeach; ?>
                                        <?php else: ?>
                                            <tr>
                                                <td class="align-middle" colspan="3">
                                                    Nothing
                                                </td>
                                            </tr>

                                        <?php endif; ?>
                                    </tbody>
                                </table> 
                                -->
                        </div>

                        <!--tutorial-->
                        <div class="tutorial-frame" type="button">
                            <label><img src="<?= BASE_URL ?>/style/css/new-images/video-circle.svg" alt="video-circle.svg""> Tutorial</label>                          
                        </div>
                        <div class="tutorial-frame-1" type="button">
                            <label><img src="<?= BASE_URL ?>/style/css/new-images/book.svg" alt="book.svg"> Guide</label>                            
                        </div>
            
                        <!--coin-name-->
        
                        <div class="coin-name">
                            <a><?= $symbol ?></a>
                        </div>
            
                        <div class="coin-suggestion">
                            <div class="text-effect <?= $referer == ('http://thealchemist.ai/en/chartpatterns' ||'http://thealchemist.ai/en/chartpatterns#') ? "text-effect-active" : "" ?>">
                                <a href="http://thealchemist.ai/en/chartpatterns">
                                Suggestion
                                </a>
                            </div>
                            <img src="<?= BASE_URL ?>/style/css/new-images/Vector 60 (Stroke).svg" alt="Vector 60 (Stroke).svg">
                            <div class="text-effect">
                                <a>
                                My Watchlist
                                </a>
                            </div>
                        </div>
                        <!--TDV JS--> 
                        <div class="tradingview-frame">
                            <div class="tradingview-widget-container mb-3">
                                <div id="crypt-candle-chart"></div>
                            </div>
                        </div>
                            <!--listcoinbox-->
                                <div class="listcoin-box">
                                    <div class="standard-box">
                                        
                                        <div class="text-effect <?php $activeList == 'st' ? _e("text-effect-active") : '' ?>">
                                            <a href="?study=<?php echo($studies) ?>&aclist=st&tab=<?php echo($tab) ?>&type=<?php echo($type) ?>">Standard<a/>
                                        </div>
                                        <img src="<?= BASE_URL ?>/style/css/new-images/Vector 60 (Stroke).svg" alt="Vector 60 (Stroke).svg">
                                        <div class="text-effect <?php $activeList == 'my' ? _e("text-effect-active") : "" ?>">
                                            <a href="?study=<?php echo($studies) ?>&aclist=my&tab=<?php echo($tab) ?>&type=<?php echo($type) ?>">My List</a>
                                        </div>
                                        <img src="<?= BASE_URL ?>/style/css/new-images/Vector 60 (Stroke).svg" alt="Vector 60 (Stroke).svg">
                                        <div class="text-effect <?php $activeList == 'pro' ? _e("text-effect-active") : "" ?>">
                                            <a href="?study=<?php echo($studies) ?>&aclist=pro&tab=<?php echo($tab) ?>&type=<?php echo($type) ?>">Pro List</a>
                                        </div>
                                    </div>
                                    <div class="tab-pane trade-container-right-tab work-form-item-tab-info-content <?= $activeList ?>">
                                        <table class="listcoin-table">
                                        
                                            <thead >
                                                <tr class="tr-bottom text_headerlist">
                                                    <th scope="col" style="color:#1A64F0;">Name &emsp;&emsp;&emsp;&emsp; Discovered on</th>
                                                </tr>
                                            </thead>

                                            <tbody class="tr-bottom text_onlist" >
                                                <?php foreach ($patternsPosts as $patternsPost): ?>
                                                <?php
                                                $timestamp = strtotime($patternsPost['date_found']);
                                                
                                                ?>
                                                <tr style="border-bottom: 1px solid #F6F6F6; height:38px;" class="<?= $postCurrent['ID'] == $patternsPost['ID'] ? "trade-coin-tr-active" : "" ?>">
                                                    <td class="align-middle">
                                                        <a class="trade-coin-a"
                                                        style="color:<?php echo strpos($patternsPost['pattern_name'], 'Bearish') !== false ? '#CC0001' : (strpos($patternsPost['pattern_name'], 'Bullish') !== false ? '#00BD46' : ''); ?>"
                                                        href="?ID=<?php echo($patternsPost['ID']) ?>&aclist=<?php _e($activeList); ?>&symbol=<?php echo($patternsPost['symbol']) ?>&tab=<?php echo($tab) ?>&type=<?php echo($type) ?>&study=<?= $studies ?>" 
                                                        data-placement="right" title="<?= $patternsPost['symbol'] ?>">
                                                            <?= get_quote(strip_tags($patternsPost['symbol']), 6) ?>
                                                        </a>
                                                    </td>
                                                    <td class="align-middle">
                                                        <span class="pr-2" data-placement="right" title="<?= $timestamp ?>">
                                                            <span class='desc'><?php echo(date("d/m", $timestamp)) ?></span>
                                                        </span>
                                                    </td>
                                                    <td class="align-middle">
                                                        <?php echo(date("H:i", $timestamp)) ?>
                                                    </td>
                                                </tr>
                                                <?php 
                                                    endforeach;
                                                ?>
                                            </tbody> 
                                        </table>
                                    </div>
                                </div>
             
                            <!--order infomation-->   
                            <div class="order-information"> 
                                <br>
                                <br>
                                   <a style="font-family: 'Poppins'; font-size: 16px; "> <strong>Order Information</strong></a>
                                        <!--Trading Pair Information-->
                                        <?php
                                        $dCurrent = $postCurrent['date'];
                                        $detail = [];
                                        if ($postCurrent) {
                                            $detail = json_decode($postCurrent['json_details']);
                                            $formular = $formulars[$postCurrent['type_id']];
                                        }
                                        ?>
                                        <div role="tabpanel" class="tab-pane <?= $activeUSD ?>" id="usd">
                                        <!--coin-name-->
                                <div class="information-box">
                                    <div class="coin-box-1">
                                        <div class="text-box-frame left-frame">
                                            <a class="title-box-1">Trading &nbsp; Pair:</a>
                                            <a class="title-box-2"> 
                                                <?= $symbol ?> 
                                            </a>
                                        </div>
                                    </div>
                                    <!--Patterm-->
                                    <div class="coin-box-1">
                                        <div class="text-box-frame left-frame">
                                            <a class="title-box-1">Detected&emsp;Pattern:</a>
                                            <a class="title-box-long"> 
                                                <?= $patternCurrent['pattern'] ?> 
                                            </a>
                                        </div>
                                    </div>
                                        <!--Entry-->
                                    <div class="coin-box-1">
                                            <div class="text-box-frame left-frame">       
                                                <a class="title-box-1" style="color:#1A64F0;">Entry &emsp; Point:</a>
                                                <a class="title-box-2" style="color:#1A64F0;"> 
                                                    <?php echo($detail->buylong)?> 
                                                </a>
                                            </div>
                                    </div>
                                        <!--Target-->
                                    <div class="coin-box-1">
                                        <div class="text-box-frame left-frame">
                                            <a style="color: #00BD46;" class="title-box-1">Target &emsp; Point:</a>
                                            <a style="color: #00BD46" class="title-box-2"> 
                                                <?php echo($detail->target3) ?> 
                                            </a>
                                        </div>
                                    </div>
                                        <!---Stop-loss-->
                                    <div class="coin-box-2">
                                        <div class="text-box-frame left-frame">
                                            <a style="color: #CC0001;" class="title-box-1">Stop Loss:</a>
                                            <a style="color: #CC0001;" class="title-box-2"> 
                                                <?php echo($detail->stoploss) ?> 
                                            </a>
                                        </div>
                                    </div>
                                        <!---Reward-->
                                    <div class="coin-box-2">
                                        <div class="text-box-frame left-frame">
                                            <a style="color: #00BD46;" class="title-box-1">Reward:</a>
                                            <a style="color: #00BD46;" class="title-box-2">     
                                                <?php echo number_format(round($detail->r2, 10), 10); ?> 
                                            </a>
                                        </div>
                                    </div>
                                        <!---Risk-->
                                    <div class="coin-box-2">
                                        <div class="text-box-frame left-frame">
                                            <a style="color: #CC0001;" class="title-box-1">Risk:</a>
                                            <a style="color: #CC0001;" class="title-box-2">
                                                <?php echo number_format(round($detail->r1, 10), 10); ?>
                                            </a>
                                        </div>
                                    </div>
                                        <!---Detected-->
                                    <div class="coin-box-1">
                                        <div class="text-box-frame left-frame">
                                            <a class="title-box-1">Detected &emsp; on:</a>
                                            <a class="title-box-2"> 
                                                <?php echo(date("d/m H:i", $postCurrent['close_time'] / 1000 + 1)) ?>
                                            </a>
                                        </div>
                                    </div>
                                            <!---Status-->
                                    <div class="coin-box-2">
                                        <div class="text-box-frame left-frame">
                                            <a class="title-box-1">Status:</a>
                                            <a class="title-box-2">
                                           
                                            <span style='color:#28D781'>Done</span>
                                            </a>
                                        </div>
                                    </div>
                        
                                    <!--End Trading Pair Information-->
                                    <!--Trading-Strategy-->
                            
                                    <div class="trading-strategy-box">
                                        <div class="trading-text-box" style="width:100%;">Detected Harmonic Price Pattern</div>
                                            <div class="detected-box">
                                                <p class="detect-box-heading"><?= $patternCurrent['pattern_name']  ?></p>
                                                <p class="detect-box-title-text">Price Movement Probability</p>
                                                
                                                <div class="detect-price-box">
                                                    <div style="display:flex">
                                                        <p class="bull">Bull:&nbsp;</p>
                                                        <p class="content"><?php echo strpos($patternCurrent['pattern_name'], 'Bearish') !== false ? '20%' : (strpos($patternCurrent['pattern_name'], 'Bullish') !== false ? '70%' : ''); ?></p>
                                                    </div>
                                                    <div class="indicator" ></div>
                                                    <div style="display:flex">
                                                        <p class="bear">Bear:&nbsp;</p>
                                                        <p class="content"><?php echo strpos($patternCurrent['pattern_name'], 'Bearish') !== false ? '70%' : (strpos($patternCurrent['pattern_name'], 'Bullish') !== false ? '20%' : ''); ?></p>
                                                    </div>
                                                    <div class="indicator" ></div>
                                                    <div style="display:flex">
                                                        <p class="other">Other:&nbsp;</p>
                                                        <p class="content">10%</p>
                                                    </div>
                                                </div>
                                                
                                                <!-- image -->
                                                <?php 
                                                    $imgUrl = $BASE_URL.'/img/patterns/';
                                                    //check type
                                                    if (strpos($patternCurrent['pattern_name'], 'Bearish') !== false) {
                                                        $imgUrl = $imgUrl.'Bear_';
                                                    } else {
                                                        $imgUrl = $imgUrl.'Bull_';
                                                    }
                                                    
                                                    //check pattern
                                                    if (strpos($patternCurrent['pattern_name'], 'Shark') !== false ) {
                                                        $imgUrl = $imgUrl.'Shark.png';
                                                    } else if (strpos($patternCurrent['pattern_name'], 'Butterfly') !== false ) {
                                                        $imgUrl = $imgUrl.'Butterfly.png';
                                                    } else if (strpos($patternCurrent['pattern_name'], 'Bat') !== false ) {
                                                        $imgUrl = $imgUrl.'Bat.png';
                                                    } else if (strpos($patternCurrent['pattern_name'], 'Cypher') !== false ) {
                                                        $imgUrl = $imgUrl.'Cypher.png';
                                                    } else if (strpos($patternCurrent['pattern_name'], 'Gartley') !== false ) {
                                                        $imgUrl = $imgUrl.'Gartley.png';
                                                    } else {
                                                        $imgUrl = $imgUrl.'Shark.png';
                                                    }
                                                    
                                                ?>
                                                <div style="margin-top:8px;">
                                                    <img src="<?= $imgUrl ?>" alt="">
                                                </div>
                                            </div>
                                            
                                            <div class="right-detected-box">
                                                <?php 
                                                    $dataWithDoubleQuotes = str_replace("'", '"', $patternCurrent['XABCD_details']);
                                                    $XABCD_details = json_decode($dataWithDoubleQuotes, true);
                                                ?>
                                                <script>
                                                    /**
                                                    console.log(`$XABCD_details: <?php var_dump($XABCD_details) ?>`)
                                                    */
                                                </script>
                                                <div class="sub-detected-box">
                                                    <p class="sub-detected-box-title">X</p>
                                                    <div class="text-field sub-detect-price">
                                                        <label>
                                                            Price
                                                        </label>
                                                        <p>
                                                        <?php
                                                            if (strpos($patternCurrent['pattern_name'], 'Bearish') !== false) {
                                                                echo number_format(round(($XABCD_details['X'])['high'], 10), 3); 
                                                            } else {
                                                                echo number_format(round(($XABCD_details['X'])['low'], 10), 3); 
                                                            }
                                                        ?>
                                                        </p>
                                                    </div>
                                                    <div class="text-field sub-detect-time">
                                                        <label>
                                                            Time
                                                        </label>
                                                        <p>
                                                            <?php 
                                                                if ($type == "D1") {
                                                                    echo date("D d M'y", ($XABCD_details['X'])['date'] / 1000);
                                                                } else if ($type == "H4"){
                                                                    echo date("H:i d M", ($XABCD_details['X'])['date_h4'] / 1000);
                                                                } else if ($type == "H1"){
                                                                    echo date("H:i d M", ($XABCD_details['X'])['date_h1'] / 1000);
                                                                } 
                                                            ?>
                                                        </p>
                                                    </div>
                                                </div>
                                                <div class="sub-detected-box">
                                                    <p class="sub-detected-box-title">A</p>
                                                    <div class="text-field sub-detect-price">
                                                        <label>
                                                            Price
                                                        </label>
                                                        <p>
                                                            <?php
                                                                if (strpos($patternCurrent['pattern_name'], 'Bearish') !== false) {
                                                                    echo number_format(round(($XABCD_details['A'])['low'], 10), 3); 
                                                                } else {
                                                                    echo number_format(round(($XABCD_details['A'])['high'], 10), 3); 
                                                                }
                                                            ?>
                                                        </p>
                                                    </div>
                                                    <div class="text-field sub-detect-time">
                                                        <label>
                                                            Time
                                                        </label>
                                                        <p>
                                                        <?php 
                                                                if ($type == "D1") {
                                                                    echo date("D d M'y", ($XABCD_details['A'])['date'] / 1000);
                                                                } else if ($type == "H4"){
                                                                    echo date("H:i d M", ($XABCD_details['A'])['date_h4'] / 1000);
                                                                } else if ($type == "H1"){
                                                                    echo date("H:i d M", ($XABCD_details['A'])['date_h1'] / 1000);
                                                                } 
                                                            ?>
                                                        </p>
                                                    </div>
                                                </div>
                                                <div class="sub-detected-box">
                                                    <p class="sub-detected-box-title">B</p>
                                                    <div class="text-field sub-detect-price">
                                                        <label>
                                                            Price
                                                        </label>
                                                        <p>
                                                            <?php
                                                            if (strpos($patternCurrent['pattern_name'], 'Bearish') !== false) {
                                                                echo number_format(round(($XABCD_details['B'])['high'], 10), 3); 
                                                            } else {
                                                                echo number_format(round(($XABCD_details['B'])['low'], 10), 3); 
                                                            }
                                                        ?>
                                                        </p>
                                                    </div>
                                                    <div class="text-field sub-detect-time">
                                                        <label>
                                                            Time
                                                        </label>
                                                        <p>
                                                        <?php 
                                                                if ($type == "D1") {
                                                                    echo date("D d M'y", ($XABCD_details['B'])['date'] / 1000);
                                                                } else if ($type == "H4"){
                                                                    echo date("H:i d M", ($XABCD_details['B'])['date_h4'] / 1000);
                                                                } else if ($type == "H1"){
                                                                    echo date("H:i d M", ($XABCD_details['B'])['date_h1'] / 1000);
                                                                } 
                                                            ?>
                                                        </p>
                                                    </div>
                                                </div>
                                                <div class="sub-detected-box">
                                                    <p class="sub-detected-box-title">C</p>
                                                    <div class="text-field sub-detect-price">
                                                        <label>
                                                            Price
                                                        </label>
                                                        <p>
                                                            <?php
                                                            if (strpos($patternCurrent['pattern_name'], 'Bearish') !== false) {
                                                                echo number_format(round(($XABCD_details['C'])['low'], 10), 3); 
                                                            } else {
                                                                echo number_format(round(($XABCD_details['C'])['high'], 10), 3); 
                                                            }
                                                        ?>
                                                        </p>
                                                    </div>
                                                    <div class="text-field sub-detect-time">
                                                        <label>
                                                            Time
                                                        </label>
                                                        <p>
                                                            <?php 
                                                                if ($type == "D1") {
                                                                    echo date("D d M'y", ($XABCD_details['C'])['date'] / 1000);
                                                                } else if ($type == "H4"){
                                                                    echo date("H:i d M", ($XABCD_details['C'])['date_h4'] / 1000);
                                                                } else if ($type == "H1"){
                                                                    echo date("H:i d M", ($XABCD_details['C'])['date_h1'] / 1000);
                                                                } 
                                                            ?>
                                                        </p>
                                                    </div>
                                                </div>
                                                <div class="sub-detected-box">
                                                    <p class="sub-detected-box-title">D</p>
                                                    <div class="text-field sub-detect-price">
                                                        <label>
                                                            Price
                                                        </label>
                                                        <p>
                                                            <?php
                                                                if (strpos($patternCurrent['pattern_name'], 'Bearish') !== false) {
                                                                    echo number_format(round(($XABCD_details['D'])['low'], 10), 3); 
                                                                } else {
                                                                    echo number_format(round(($XABCD_details['D'])['high'], 10), 3); 
                                                                }
                                                            ?>
                                                        </p>
                                                    </div>
                                                    <div class="text-field sub-detect-time">
                                                        <label>
                                                            Time
                                                        </label>
                                                        <p>
                                                        <?php 
                                                                if ($type == "D1") {
                                                                    echo date("D d M'y", ($XABCD_details['D'])['date'] / 1000);
                                                                } else if ($type == "H4"){
                                                                    echo date("H:i d M", ($XABCD_details['D'])['date_h4'] / 1000);
                                                                } else if ($type == "H1"){
                                                                    echo date("H:i d M", ($XABCD_details['D'])['date_h1'] / 1000);
                                                                } 
                                                            ?>
                                                        </p>
                                                    </div>
                                                </div>
                                                
                                            </div>
                                        </div>
                                            
                                            <!--button-Save-order-->
                                            <div class="save-button-frame">
                                                <?php if ($this->save): ?>
                                                <button class="save-order-button trade-container-bottom-item2-save" disabled"><a><b>Processing</b></a>

                                                <?php else: ?>
                                                    <button class="save-order-button trade-container-bottom-item2-save" rel-id="<?= $postCurrent['subID'] ?>" rel-type="<?= $postCurrent['type'] ?>"><a><b>Save</b><a></button>
                                                <?php endif; ?>
                                            </div>
                                           
                                            <div class="save-text-notice">
                                                <?php if ($this->save): ?>
                                                    Your investment is being analyzed in &nbsp;<a href="profile">My Dashboard</a>
                                                <?php else: ?>
                                                    Please keep in mind that these are only suggestions,
                                                    <br>consider them carefully before trading!
                                                <?php endif; ?>
                                                </a>
                                            </div>
                                            </div>
                        
                                            <!--bottom-right-box-->
                                                
                                            <div class="top-bottom-right" <?= $activeUSD ?>" id="usd">
                                                    <a style="position: absolute;
                                                    width: 180px;
                                                    left: calc(50% - 180px/2);
                                                    top: 24px; font-size: 18px; font-family: 'Poppins'; font-weight: 700;">How to trade with Candlestick</a>
                                                    <div class="text-model-information">
                                               
                                                        <div class="infomartion-frame model-name">
                                                                <a class="model-text-box" style="text-align: left;">Model:</a>
                                                                <a  href='#' class="model-name">
                                                                    <?= $postCurrent['model_title'] ?? $formular['title'] ?>
                                                                </a>
                                                        </div>
                                                    </div>
                                                    <div class="learn-now-box">
                                                        <a href="http://thealchemist.ai/en/academy" >No idea what
                                                            <?= $postCurrent['model_title'] ?? $formular['title'] ?> is?
                                                        
                                                        <br>
                                                        <b>Learn now!
                                                        </b>  
                                                        </a>
                                                    </div>
                                                    
                                                    <div class="myformula-text-box">
                                                        <a href="http://thealchemist.ai/en/work" style="color: #7D7D7D;">Got a strategy? Turn it into an algorithm with <a href="work" style="color:#1A64F0;">
                                                        <b>My Formula</b></a>
                                                    </div>
                                            </div>

                                            <div class="bottom-right-box-end">
                                                    <a class="text-box-manage">Manage your Portfolio</a>
                                                    <div class="image-box-manage">
                                                        <img src="<?= BASE_URL ?>/style/css/new-images/manage-img.svg" alt="portorio">
                                                    </div> 
                                                    <button class="button-go-dashboard">
                                                        <a href="profile" style="color: white;">Go to <b>My Dashboard</b></a>
                                                    </button>
                                           </div>
                            </div>
            </div>
        </div>
</div>

</div>
</div>
<!--footer-->
<?php include __DIR__ . '/layouts/footer.phtml'; ?>
<!--End footer-->  

<!--popup connect wallet-->
<?php include __DIR__ . '/layouts/pop.phtml'; ?>
<!--End popup connect wallet--> 
<?php include __DIR__ . '/layouts/scrips.phtml'; ?>

         <script src="<?= BASE_URL ?>/style/js/tv.js"></script>
        <script src="<?= BASE_URL ?>/style/js/new/tv.js"></script>
        <script src="<?= BASE_URL ?>/style/js/new/mainh4.js"></script>
        <script  type="text/javascript">
            var studies = <?php echo json_encode($study); ?>;
            if (document.getElementById('crypt-candle-chart')) {
                new TradingView.widget(
                        {
                            "autosize": true,
                            "symbol": "BTCUSDT",
                            "interval": "<?php echo($interval); ?>",
                            "timezone": "Asia/Bangkok",
                            "theme": "Light",
                            "style": "1",
                            "locale": "en_EN",
                            "toolbar_bg": "rgba(255, 255, 255, 1)",
                            "enable_publishing": false,
                            "allow_symbol_change": true,
                            "show_popup_button": true,
                            "popup_width": "1000",
                            "popup_height": "1000",
                            "withdateranges": true,
                            "container_id": "crypt-candle-chart",
                            "studies_overrides": {
                                "rsi.rsi.plot.color": "#2196f3",
                                "rsi.level.0": 20,
                                "rsi.level.1": 80
                            },
                            "studies": studies
                        }
                );
            }
        </script>
    </body>
    </html>