<div class="adminleft">
    <ul id="menu_left">
        <li class="big_link"><a href="">Công thức </a></li>
        <li class="sub_link"><a href="<?= $this->moduleUrl ?>/product">Tất cả công thức</a></li>
        <li class="sub_link"><a href="<?= $this->moduleUrl ?>/product/cat">Danh sách thư mục</a></li>
        <li class="sub_link"><a href="<?= $this->moduleUrl ?>/product/addcat">Thêm thư mục</a></li>
        <li class="sub_link"><a href="<?= $this->moduleUrl ?>/product/faq">Faq</a></li>
    </ul>
</div>