
<?php if (isset($this->message)): ?>
    <div class="error">	<?= $this->translate($this->message); ?></div>
<?php endif; ?>

<?php if ($this->message != "ERROR_MSQL" AND $this->message != "ERROR_NO_CATELOGY_EXISTS"): ?>
    <form action="<?= $this->actionUrl ?>" method="post" enctype="multipart/form-data">
        <input type="hidden" name="ID" value="<?= $this->ID ?>"/>
        <div class="wrap_admintab">
            <?php include "_menu.phtml" ?>
            <div class="adminright">
                <div class="admintab" style="min-height:376px;padding:0px;">
                    <table cellpadding="8" border="1" bordercolor="#d9d9d9" width="100%">
                        <tr>
                            <td><label>Tên công thức</label></td>
                            <td><input type="text" name="title" size="60" class="itext" value="<?= $this->title ?>" /></td>
                        </tr>
                        <tr>
                            <td><label>Loại nến</label></td>
                            <td><?= $this->catOptions ?></td>
                        </tr>

                        <tr>
                            <td><label>Public nến</label></td>
                            <td><?= $this->catTypes ?></td>
                        </tr>

                        <tr>
                            <td><label>Ảnh đại diện</label></td>
                            <td>
                                <table>
                                    <tr><td style="border:none;"><input type="file" name="img"/></td></tr>
                                    <tr>
                                        <?php if (strlen($this->img) > 0) : ?>
                                            <td width="20"><img  width="100" height="100" src="<?= BASE_URL ?>/<?= $this->dirImage ?>/<?= $this->img ?>"/></td>
                                            <td><a href="<?= $this->moduleUrl ?>/product/delimg?ID=<?= $this->id ?>" class="delimg">delete</a></td>
                                        <?php endif; ?>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td><label>Đường dẫn ảnh</label></td>
                            <td><input type="text" name="link_url" size="60" class="itext" value="<?= $this->link_url ?>" /></td>
                        </tr>
                        <tr>
                            <td><label>Entry Zone</label></td>
                            <td><input type="text" name="buylong" size="60" class="itext" value="<?= $this->buylong ?>" /></td>
                        </tr>
                        <tr>
                            <td><label>DCA1</label></td>
                            <td><input type="text" name="target1" size="60" class="itext" value="<?= $this->target1 ?>" /></td>
                        </tr>
                        <tr>
                            <td><label>DCA2</label></td>
                            <td><input type="text" name="target2" size="60" class="itext" value="<?= $this->target2 ?>" /></td>
                        </tr>
                        <tr>
                            <td><label>Target Zone</label></td>
                            <td><input type="text" name="target3" size="60" class="itext" value="<?= $this->target3 ?>" /></td>
                        </tr>
                        <tr>
                            <td><label>Stop Loss</label></td>
                            <td><input type="text" name="stoploss" size="60" class="itext" value="<?= $this->stoploss ?>" /></td>
                        </tr>
                        <tr>
                            <td><label>Risk</label></td>
                            <td><input type="text" name="r1" size="60" class="itext" value="<?= $this->r1 ?>" /></td>
                        </tr>
                        <tr>
                            <td><label>Reward</label></td>
                            <td><input type="text" name="r2" size="60" class="itext" value="<?= $this->r2 ?>" /></td>
                        </tr>

                        <tr>
                            <td><label>Formula</label></td>
                            <td align="left">
                                <textarea  name="desc" rows="6" cols="61"><?= htmlspecialchars_decode($this->desc) ?></textarea>
                            </td>

                        </tr>
                        <tr>
                            <td colspan="2" align="center">
                                <input type="submit" value="Sửa công thức"/>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>

    </form>
<?php endif; ?>