
<div class="wrap_admintab">
    <?php include "_menu.phtml" ?>
    <div class="adminright">

        <div class="admintab" style="min-height:376px;padding:0px;">
            <div id="tkiem">
                <ul >
                    <form action="<?= $this->actionUrl ?>" class="formajax">
                        <li class="form_h">
                            <?php echo($abc); ?>  Tìm kiếm:  <input type="text" name="s" class="itext hh_s" size="25" style="color:#8e8e8e; font-style:italic;padding:3px;"  />&nbsp;<input type="submit" class="search" title="<?= $this->translate('Find post') ?>"/>

                        </li>
                    </form>
                </ul>

                <h3 class="add_link"><a href="<?= $this->controllerUrl ?>/add<?= $this->action ?>" class="add"></a></h3>

            </div>
            <div style="clear:both"></div>
            <div style="padding:5px;color:#aaa">
                <?php if ($this->postBad AND count($this->postBad) > 0): ?>
                    <a href="<?= $this->controllerUrl ?>/?parent_id=0" <?= $this->translate('Posts have no parent') ?> class="post_no_parent ajax"><?= $this->postBad ?></a> / <?php endif; ?><?= $this->totalPost ?>
            </div>
            <form action="<?= $this->controllerUrl ?>/delete<?= $this->action ?>" method="post" class="formajax">
                <?= $this->pageBar ?>
                <table cellpadding="8" border="1" bordercolor="#d9d9d9" style="border-collapse:collapse" width="100%" align="center">
                    <tr>
                        <th><?= $this->translate("ID") ?></th>
                        <th>Ảnh</th>
                        <th><?= $this->translate("Title") ?></th>
                        <th><?= $this->translate("Parent") ?></th>
                        <th><?= $this->translate("Date") ?></th>
                        <th>Public nến</th>
                        <th><?= $this->translate("Poster") ?></th>
                        <th><?= $this->translate("Editer") ?></th>
                        <th><?= $this->translate("Edit") ?></th>
                        <th><?= $this->translate("Delete") ?></th>
                        <th><input type="checkbox" onclick="checkAll(this)"/></th>
                    </tr>
                    <?php foreach ($this->posts as $key => $post): ?>
                        <tr>
                            <td align="center"><?= $key + 1 ?></td>
                            <td align="center"><img  style="max-width:120px" height="90" src="<?= BASE_URL ?>/<?= $this->dirImage ?>/<?= $post['img'] ?>"/></td>
                            <td>
                                <a class="quick_edit_title" u="<?= $this->controllerUrl ?>/edit<?= $this->action ?>/?ID=<?= $post['ID'] ?>">
                                    <?= $post['sticky'] != '0' ? '<b style="color:red">' . $post['sticky'] . '. </b>' : '' ?><?= $post['title'] ?><?= $post['has_video'] == '1' ? "<sup><i class='has_video'></i></sup>" : "" ?><?= $post['has_img'] == '1' ? "<sub><i class='has_image'></i></sub>" : "" ?></a>
                            </td>
                            <td align="center" nowrap="nowrap">
                                <label class="ajax"><?= $post['cat_link'] ?></label>
                            </td>
                            <td align="center"><?= $post['date'] <= $this->Plugins->time() ? date("H:i:s d/m/Y", $post['date']) : ("<span class='nextdate'>" . date("H:i:s d/m/Y", $post['date']) . "</span>") ?></td>
                            <td align="center">
                                <?php $post['method'] == 'PUBLIC' ? _e('Cho phép') : _e('Không cho phép') ?>

                            </td>

                            <td align="center"><span title="<?= @date("H:i:s d/m/Y", $post['date_post']) ?>"><?= @$post['user_post'] ?></span></td>

                            <td align="center"><?php if (isset($post['user_edit'])): ?><span title="<?= date("H:i:s d/m/Y", $post['date_edit']) ?>"><?= $post['user_edit'] ?></span><?php endif; ?></td>
                            <td align="center">
                                <a href="<?= $this->controllerUrl ?>/edit<?= $this->action ?>/?ID=<?= $post['ID'] ?>" class="edit"></a>
                            </td>
                            <td align="center">
                                <a href="<?= $this->controllerUrl ?>/delete<?= $this->action ?>/?ID=<?= $post['ID'] ?>" class="delete"></a>
                            </td>
                            <td align="center"><input type="checkbox" size="1" value="<?= $post['ID'] ?>" name="ID[]"/></td>
                        </tr>
                    <?php endforeach; ?>
                    <?php if (isset($key)): ?>
                        <tr>
                            <td colspan="8" align="right">
                                <?= $this->catOptions ?>
                            </td>
                            <td align="center">
                                <input type="submit" class="deleteall" onclick="$('input.moveall').remove()" title="<?= $this->translate('Delete selected posts') ?>"/>
                            </td>
                            <td align="center">
                                <input type="submit" name="act_move" class="moveall" title="<?= $this->translate('Move selected posts') ?>"/>
                            </td>
                        </tr>
                    <?php else: ?>
                        <tr>
                            <td colspan="10" align="center">
                                <?= $this->translate("Nothing found") ?>
                            </td>
                        </tr>
                    <?php endif; ?>
                </table>
                <?= $this->pageBar ?>
            </form>
            <div>
                <br>
                <a href="https://thealchemist.ai/vn/cron">Tính toán lại công thức</a></h3>

            </div>
        </div>
    </div>
</div>